title: Michaël Fery
description: >- # this means to ignore newlines until "baseurl:"
  Michaël Fery
  Senior Consultant & \#Azure \#MVP
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mfery.com"
twitter_username: _mfery
github_username:  michaelfery

# Author Settings
author: Michaël Fery
author-img: michael-fery.png
about-author: I am a developer focusing on Cloud and DevOps. Always hungry to keep learning. # add description
social-twitter: _mfery
social-github: michaelfery
social-linkedin: mfery

# Tracker
analytics: UA-90543822-1 # Google Analytics

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji

paginate: 8
paginate_path: "/page/:num"

future: false

permalink: '/:year/:month/:title'

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
